name: gr_dhp
channels:
  - menpo
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - pip=19.3.1=py37_0
  - python=3.7.5=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=42.0.2=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.8.1
    - astor==0.8.0
    - cachetools==3.1.1
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.1
    - gast==0.2.2
    - google-auth==1.7.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.25.0
    - h5py==2.10.0
    - idna==2.8
    - imageio==2.6.1
    - imgaug==0.3.0
    - imutils==0.5.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==3.1.2
    - networkx==2.4
    - numpy==1.17.4
    - oauthlib==3.1.0
    - opencv-contrib-python==4.1.2.30
    - opencv-python-headless==4.1.2.30
    - opt-einsum==3.1.0
    - pillow==6.2.1
    - protobuf==3.11.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.7
    - pyparsing==2.4.5
    - python-dateutil==2.8.1
    - pywavelets==1.1.1
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-image==0.16.2
    - scipy==1.3.3
    - shapely==1.6.4.post2
    - six==1.13.0
    - tensorboard==2.0.2
    - tensorflow==2.0.0
    - tensorflow-estimator==2.0.1
    - termcolor==1.1.0
    - torch==1.3.1
    - urllib3==1.25.7
    - werkzeug==0.16.0
    - wrapt==1.11.2

